live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[font.offset]
x = 0

[window]
decorations = "full"
opacity = 0.9

[window.padding]
x = 4
y = 9
